#!/usr/bin/env bash
#/ Usage: script/bootstrap
#/
#/ Resolve all dependencies.
#/

set -e

# if help requested, print the comments at the top of the file
[[ "$1" == "-h" || "$1" =~ "(--)?help" ]] && {
  grep "^#/" < "$0" | cut -c4-
  exit 0
}

cd "$(dirname "$0")/.."

echo "==> Resolving dependencies..."

command -v brew >/dev/null && {
  brew bundle check --verbose --file=Brewfile  || {
    echo "==> Installing missing dependencies via Homebrew..."
    brew bundle install --verbose --file=Brewfile --no-lock
  }
}
