#!/bin/bash
#/ Usage: script/setup
#/
#/ Symlink all scripts from $SOURCE_BIN_DIR to $TARGET_BIN_DIR
#/

set -e

# if help requested, print the comments at the top of the file
if [ "$1" = "--help" -o "$1" = "-h" -o "$1" = "help" ]; then
  grep "^#/" < "$0" | cut -c4-
  exit 0
fi

cd "$(dirname "$0")/.."

SOURCE_BIN_DIR="bin"
TARGET_BIN_DIR="$HOME/bin"

if [ ! -d "TARGET_BIN_DIR" ]; then
    echo "==> $TARGET_BIN_DIR doesn't yet exist, creating it"
    mkdir "$TARGET_BIN_DIR"
fi

if [ ! $(echo "$PATH" | grep "$TARGET_BIN_DIR") ]; then
    echo "$TARGET_BIN_DIR not in PATH, adding it"
    # export PATH="$PATH:$TARGET_BIN_DIR"
fi

for f in $(ls "$SOURCE_BIN_DIR"); do
    ln -sf "$f" "$TARGET_BIN_DIR/$f"
done

echo "==> Setup done"
